[WIP] Support Binaries Repo customization
fergusstrange/embedded-postgres pull request #65
Opened 2022-02-16 15:17 UTC by bulanovk

Support maven repo overriding in case of execution behind the firewall

2022-02-21 03:00 UTC, fergusstrange requested changes
Looks like a valuable change, thanks for the contribution.

2022-02-21 07:19 UTC, bulanovk commented on config.go
> +	binariesRepo string
Yes, you are right BinaryRepositoryURL will make it more clear to understand

2022-03-02 03:57 UTC, fergusstrange approved these changes

2022-03-02 03:57 UTC, merged

2022-03-02 03:57 UTC, fergusstrange commented
Nice one @bulanovk thanks for your changes. I'll cut a release on this now.

2022-03-02 04:35 UTC, fergusstrange commented
@bulanovk release [here](https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.15.0)